# Imports

In [1]:
import pandas as pd
import numpy as np
import os


# turn off pink warning boxes
import warnings
warnings.filterwarnings("ignore")
import acquire
import prepare

In [2]:
# df_cohort_list = list(df.cohort.value_counts().index)

In [3]:
# for cohort in df_cohort_list:
#     if cohort != 'Everglades':
        
#         cohort_df = pd.DataFrame(df[(df.endpoint != '/')].groupby('cohort')['endpoint'].value_counts())
#         cep_df = cohort_df.loc[[cohort]]
#         cep_df = cep_df.endpoint.nlargest(3)
#         print(cep_df)
#         print('\n')

# Acquire

In [4]:
df= acquire.acquire()

In [5]:
df.head()

,date,endpoint,user_id,cohort_id,source_ip,name,start_date,end_date,created_at,updated_at,program_id
0,2018-01-26,/,1,8.0,97.105.19.61,Hampton,2015-09-22,2016-02-06,2016-06-14 19:52:26,2016-06-14 19:52:26,1.0
1,2018-01-26,java-ii,1,8.0,97.105.19.61,Hampton,2015-09-22,2016-02-06,2016-06-14 19:52:26,2016-06-14 19:52:26,1.0
2,2018-01-26,java-ii/object-oriented-programming,1,8.0,97.105.19.61,Hampton,2015-09-22,2016-02-06,2016-06-14 19:52:26,2016-06-14 19:52:26,1.0
3,2018-01-26,slides/object_oriented_programming,1,8.0,97.105.19.61,Hampton,2015-09-22,2016-02-06,2016-06-14 19:52:26,2016-06-14 19:52:26,1.0
4,2018-01-26,javascript-i/conditionals,2,22.0,97.105.19.61,Teddy,2018-01-08,2018-05-17,2018-01-08 13:59:10,2018-01-08 13:59:10,2.0

In [6]:
#Looking at missing values
acquire.miss_dup_values(df)

Your selected dataframe has 11 columns.
There are 8 columns that have missing values.

** There are 394392 duplicate rows that represents 38.71% of total Values**

            Missing Values  % of Total Values
name                 64497                6.3
start_date           64497                6.3
end_date             64497                6.3
created_at           64497                6.3
updated_at           64497                6.3
program_id           64497                6.3
cohort_id            53497                5.3
endpoint                 1                0.0

# Prepare

In [7]:
df= prepare.prepare(df)

In [8]:
df.head()

,endpoint,user_id,cohort_id,source_ip,name,start_date,end_date,created_at,updated_at,program_id
date,,,,,,,,,,
2018-01-26,/,1,8.0,97.105.19.61,Hampton,2015-09-22,2016-02-06,2016-06-14 19:52:26,2016-06-14 19:52:26,1.0
2018-01-26,java-ii,1,8.0,97.105.19.61,Hampton,2015-09-22,2016-02-06,2016-06-14 19:52:26,2016-06-14 19:52:26,1.0
2018-01-26,java-ii/object-oriented-programming,1,8.0,97.105.19.61,Hampton,2015-09-22,2016-02-06,2016-06-14 19:52:26,2016-06-14 19:52:26,1.0
2018-01-26,slides/object_oriented_programming,1,8.0,97.105.19.61,Hampton,2015-09-22,2016-02-06,2016-06-14 19:52:26,2016-06-14 19:52:26,1.0
2018-01-26,javascript-i/conditionals,2,22.0,97.105.19.61,Teddy,2018-01-08,2018-05-17,2018-01-08 13:59:10,2018-01-08 13:59:10,2.0

In [9]:
#Looking at missing values after prepare function
acquire.miss_dup_values(df)

Your selected dataframe has 10 columns.
There are 4 columns that have missing values.

** There are 805477 duplicate rows that represents 79.06% of total Values**

            Missing Values  % of Total Values
created_at           64497                6.3
updated_at           64497                6.3
cohort_id            53497                5.3
name                 53497                5.3

# 2. Is there a cohort that referred to a lesson significantly more than other cohorts seemed to gloss over?

In [10]:
# creating dataframe for full stack program
# full_stack_df= df[df['program_id']==1]

In [11]:
# full_stack_df.head()

In [12]:
# creating datafrane for java program
# java_df= df[df['program_id']==2]

In [13]:
# java_df.head()

In [14]:
# creating dataframe for data science program
# ds_df= df[df['program_id']==3]

In [15]:
# ds_df.head()

In [16]:
# creating dataframe for front end program
# front_end_df= df[df['program_id']==4]

In [17]:
# front_end_df.head()

In [18]:
#Looking at cohort endpoint value counts
#excluding '/'
cohort_pv_df = pd.DataFrame(df[df.endpoint != '/'].groupby('cohort_id')['endpoint'].value_counts())

In [19]:
#Renaming column in cohort_pv_df
cohort_pv_df.rename(columns={'endpoint':'endpoint_count'}, inplace= True)

In [20]:
#Looking at values
cohort_pv_df.head()

                                                              endpoint_count
cohort_id endpoint
1.0       javascript-i                                                   702
          javascript-i/javascript-with-html                              683
          html-css                                                       652
          javascript-i/introduction/working-with-data-typ...             451
          html-css/css-ii/bootstrap-grid-system                          379

In [21]:
#Looking at keys of cohort id
cohort_pv_df.keys()

Index(['endpoint_count'], dtype='object')

In [22]:
# most_pageviews_df= pd.DataFrame(columns={'cohort_id'})

In [23]:
# most_pageviews_df

In [24]:
# var= cohort_pv_df.loc[1]

In [25]:
# type(var)

In [26]:
# var.nlargest(1, 'endpoint_count')

In [27]:
# most_pageviews_df= most_pageviews_df.append(var.nlargest(1, 'endpoint_count')).reset_index()

In [28]:
# most_pageviews_df

In [29]:
# most_pageviews_df['cohort_id']= 1

In [30]:
# most_pageviews_df

In [31]:
# most_pageviews_df

In [32]:
# most_pageviews_df= pd.DataFrame(columns={'cohort_id'})

# for cohort in cohort_list:
#     var= cohort_pv_df.loc[cohort]
#     most_pageviews_df= most_pageviews_df.append(var.nlargest(1, 'endpoint_count'))
#     most_pageviews_df['cohort_id']= cohort
#     print(most_pageviews_df)

In [33]:
#reset index to make list
new= cohort_pv_df.reset_index()

In [34]:
#Making cohort list
cohort_list =list(new.cohort_id.value_counts().index)

In [35]:
#Loop to to see most pages viewed by cohort

most_pageviews_df= pd.DataFrame(columns={'cohort_id'})

for cohort in cohort_list:
    var= cohort_pv_df.loc[cohort]
    y = var.nlargest(1, 'endpoint_count')
#     most_pageviews_df['cohort_id']= cohort
    most_pageviews_df= pd.concat([most_pageviews_df, y], ignore_index = False)

In [36]:
#Looking at values after for loop
most_pageviews_df

                                                   cohort_id  endpoint_count
javascript-i                                             NaN          2101.0
spring                                                   NaN           754.0
1-fundamentals/modern-data-scientist.jpg                 NaN           653.0
index.html                                               NaN           877.0
6-regression/1-overview                                  NaN           595.0
javascript-i                                             NaN           702.0
toc                                                      NaN           991.0
classification/overview                                  NaN          1137.0
mkdocs/search_index.json                                 NaN           721.0
javascript-i                                             NaN           128.0
javascript-i                                             NaN           889.0
javascript-i                                             NaN           651.0
toc                                                      NaN           638.0
index.html                                               NaN            84.0
search/search_index.json                                 NaN           773.0
javascript-i                                             NaN            69.0
content/laravel/intro                                    NaN            39.0
toc                                                      NaN          1465.0
toc                                                      NaN           698.0
spring                                                   NaN           364.0
search/search_index.json                                 NaN          1382.0
search/search_index.json                                 NaN          1157.0
javascript-i                                             NaN           911.0
toc                                                      NaN          1888.0
search/search_index.json                                 NaN          1527.0
toc                                                      NaN          1359.0
javascript-i                                             NaN           727.0
fundamentals/modern-data-scientist.jpg                   NaN           758.0
java-iii                                                 NaN            57.0
search/search_index.json                                 NaN           669.0
toc                                                      NaN          1033.0
toc                                                      NaN           972.0
classification/scale_features_or_not.svg                 NaN           561.0
javascript-i                                             NaN           741.0
toc                                                      NaN          1298.0
toc                                                      NaN          1037.0
java-i                                                   NaN            19.0
content/html-css                                         NaN            42.0
javascript-i                                             NaN           894.0
spring                                                   NaN            65.0
fundamentals/data-science-modules.jpg                    NaN           568.0
content/html-css                                         NaN            19.0
html-css                                                 NaN            12.0
javascript-i/introduction/working-with-data-typ...       NaN           251.0
javascript-ii/es6                                        NaN            10.0
content/php_ii/command-line                              NaN             6.0
content/html-css                                         NaN             2.0
mkdocs/search_index.json                                 NaN             1.0

In [37]:
#set cohort id column to cohort list
most_pageviews_df['cohort_id']= cohort_list

In [38]:
#sorting values, resetting index, set_index, and renaming columns
most_pageviews_df= most_pageviews_df.sort_values(by='cohort_id').reset_index().set_index('cohort_id').rename(columns={'index':'endpoint'})

In [39]:
#Looking at values
most_pageviews_df

                                                    endpoint  endpoint_count
cohort_id
1.0                                             javascript-i           702.0
2.0                              content/php_ii/command-line             6.0
4.0                                 mkdocs/search_index.json             1.0
6.0                                        javascript-ii/es6            10.0
7.0                                         content/html-css            42.0
8.0                                                 java-iii            57.0
9.0                                         content/html-css             2.0
11.0                                                html-css            12.0
12.0                                        content/html-css            19.0
13.0                                              index.html            84.0
14.0                                              index.html           877.0
15.0                                                  java-i            19.0
16.0                                                  spring            65.0
17.0                                            javascript-i           128.0
18.0                                            javascript-i            69.0
19.0                                   content/laravel/intro            39.0
21.0                                                  spring           364.0
22.0                                                  spring           754.0
23.0                                mkdocs/search_index.json           721.0
24.0                                            javascript-i           889.0
25.0                                                     toc           991.0
26.0                                            javascript-i           727.0
27.0                                                     toc           698.0
28.0                                            javascript-i          2101.0
29.0                                                     toc          1465.0
31.0                                                     toc           638.0
32.0                                search/search_index.json           773.0
33.0                                search/search_index.json          1382.0
34.0                1-fundamentals/modern-data-scientist.jpg           653.0
51.0                                            javascript-i           911.0
52.0                                                     toc           972.0
53.0                                                     toc          1298.0
55.0                                 6-regression/1-overview           595.0
56.0                                search/search_index.json          1527.0
57.0                                search/search_index.json          1157.0
58.0                                                     toc          1033.0
59.0                                 classification/overview          1137.0
61.0                                search/search_index.json           669.0
62.0                                                     toc          1888.0
132.0                                           javascript-i           651.0
133.0               classification/scale_features_or_not.svg           561.0
134.0                                           javascript-i           741.0
135.0                                                    toc          1359.0
137.0                 fundamentals/modern-data-scientist.jpg           758.0
138.0                                                    toc          1037.0
139.0                                           javascript-i           894.0
165.0                  fundamentals/data-science-modules.jpg           568.0
166.0      javascript-i/introduction/working-with-data-ty...           251.0

In [59]:
most_pageviews_df.groupby('endpoint').count().sort_values(by='endpoint_count', ascending= False)

                                                    endpoint_count
endpoint
toc                                                             10
javascript-i                                                    10
search/search_index.json                                         5
spring                                                           3
content/html-css                                                 3
mkdocs/search_index.json                                         2
index.html                                                       2
fundamentals/data-science-modules.jpg                            1
fundamentals/modern-data-scientist.jpg                           1
html-css                                                         1
6-regression/1-overview                                          1
java-i                                                           1
java-iii                                                         1
content/php_ii/command-line                                      1
javascript-i/introduction/working-with-data-typ...               1
javascript-ii/es6                                                1
content/laravel/intro                                            1
classification/scale_features_or_not.svg                         1
classification/overview                                          1
1-fundamentals/modern-data-scientist.jpg                         1

In [46]:
#Loop to to see least pages viewed by cohort

least_pageviews_df= pd.DataFrame(columns={'cohort_id'})

for cohort in cohort_list:
    var= cohort_pv_df.loc[cohort]
    y2 = var.nsmallest(1, 'endpoint_count')
#     most_pageviews_df['cohort_id']= cohort
    least_pageviews_df= pd.concat([least_pageviews_df, y2], ignore_index = False)

In [47]:
#Looking at values after for loop
least_pageviews_df

                                                   cohort_id  endpoint_count
'                                                        NaN             1.0
1-fundamentals/1-fundamentals-overview                   NaN             1.0
10-anomaly-detection/3-discrete-probabilistic-m...       NaN             1.0
1-fundamentals/1.1-intro-to-data-science                 NaN             1.0
%20https://github.com/RaulCPena                          NaN             1.0
0_Classification_Algorithms                              NaN             1.0
02_listing_files                                         NaN             1.0
.gitignore                                               NaN             1.0
1-fundamentals/1-fundamentals-overview                   NaN             1.0
appendix/capstone-workbook/sw-project-planning           NaN             1.0
.git                                                     NaN             1.0
.                                                        NaN             1.0
1-fundamentals/1.1-intro-to-data-science                 NaN             1.0
appendix/capstone-workbook/sw-project-planning           NaN             1.0
1-fundamentals/1.2-data-science-pipeline                 NaN             1.0
1._Fundamentals                                          NaN             1.0
1-fundamentals/2.4-more-excel-features                   NaN             1.0
1-fundamentals/1-fundamentals-overview                   NaN             1.0
1-fundamentals/pipeline-demo                             NaN             1.0
1-fundamentals/1.2-data-science-pipeline                 NaN             1.0
1-fundamentals/3-vocabulary                              NaN             1.0
alumni                                                   NaN             1.0
1-fundamentals/2.2-excel-functions                       NaN             1.0
appendix/angular/dependencies                            NaN             1.0
appendix/cover-letter                                    NaN             1.0
ajax                                                     NaN             1.0
3.0-mysql-overview                                       NaN             1.0
advanced-topics/building-a-model                         NaN             1.0
0_Classification_Algorithms                              NaN             1.0
RESTful-api                                              NaN             1.0
appendix/further-reading/css-grid-additional-fe...       NaN             1.0
appendix/coding-challenges                               NaN             1.0
10_Project                                               NaN             1.0
appendix/angular/models                                  NaN             1.0
appendix/angular/controllers                             NaN             1.0
appendix/extra-challenges/java-file-io-extras            NaN             1.0
appendix/angular                                         NaN             1.0
appendix                                                 NaN             1.0
appendix/angular                                         NaN             1.0
appendix/capstone-workbook                               NaN             1.0
advanced-topics/cross-validation                         NaN             1.0
appendix/git/intellij-intro                              NaN             1.0
appendix/capstone-workbook                               NaN             1.0
appendix/coding-challenges/amateur                       NaN             1.0
11._DistributedML                                        NaN             1.0
content/git                                              NaN             1.0
content/html-css/gitbook/images/favicon.ico              NaN             1.0
mkdocs/search_index.json                                 NaN             1.0

In [48]:
#set cohort id column to cohort list
least_pageviews_df['cohort_id']= cohort_list

In [49]:
#verify cohort ids added
least_pageviews_df

                                                    cohort_id  endpoint_count
'                                                        28.0             1.0
1-fundamentals/1-fundamentals-overview                   22.0             1.0
10-anomaly-detection/3-discrete-probabilistic-m...       34.0             1.0
1-fundamentals/1.1-intro-to-data-science                 14.0             1.0
%20https://github.com/RaulCPena                          55.0             1.0
0_Classification_Algorithms                               1.0             1.0
02_listing_files                                         25.0             1.0
.gitignore                                               59.0             1.0
1-fundamentals/1-fundamentals-overview                   23.0             1.0
appendix/capstone-workbook/sw-project-planning           17.0             1.0
.git                                                     24.0             1.0
.                                                       132.0             1.0
1-fundamentals/1.1-intro-to-data-science                 31.0             1.0
appendix/capstone-workbook/sw-project-planning           13.0             1.0
1-fundamentals/1.2-data-science-pipeline                 32.0             1.0
1._Fundamentals                                          18.0             1.0
1-fundamentals/2.4-more-excel-features                   19.0             1.0
1-fundamentals/1-fundamentals-overview                   29.0             1.0
1-fundamentals/pipeline-demo                             27.0             1.0
1-fundamentals/1.2-data-science-pipeline                 21.0             1.0
1-fundamentals/3-vocabulary                              33.0             1.0
alumni                                                   57.0             1.0
1-fundamentals/2.2-excel-functions                       51.0             1.0
appendix/angular/dependencies                            62.0             1.0
appendix/cover-letter                                    56.0             1.0
ajax                                                    135.0             1.0
3.0-mysql-overview                                       26.0             1.0
advanced-topics/building-a-model                        137.0             1.0
0_Classification_Algorithms                               8.0             1.0
RESTful-api                                              61.0             1.0
appendix/further-reading/css-grid-additional-fe...       58.0             1.0
appendix/coding-challenges                               52.0             1.0
10_Project                                              133.0             1.0
appendix/angular/models                                 134.0             1.0
appendix/angular/controllers                             53.0             1.0
appendix/extra-challenges/java-file-io-extras           138.0             1.0
appendix/angular                                         15.0             1.0
appendix                                                  7.0             1.0
appendix/angular                                        139.0             1.0
appendix/capstone-workbook                               16.0             1.0
advanced-topics/cross-validation                        165.0             1.0
appendix/git/intellij-intro                              12.0             1.0
appendix/capstone-workbook                               11.0             1.0
appendix/coding-challenges/amateur                      166.0             1.0
11._DistributedML                                         6.0             1.0
content/git                                               2.0             1.0
content/html-css/gitbook/images/favicon.ico               9.0             1.0
mkdocs/search_index.json                                  4.0             1.0

In [50]:
#sorting values, resetting index, set_index, and renaming columns
least_pageviews_df= least_pageviews_df.sort_values(by='cohort_id').reset_index().set_index('cohort_id').rename(columns={'index':'endpoint'})

In [51]:
least_pageviews_df

                                                    endpoint  endpoint_count
cohort_id
1.0                              0_Classification_Algorithms             1.0
2.0                                              content/git             1.0
4.0                                 mkdocs/search_index.json             1.0
6.0                                        11._DistributedML             1.0
7.0                                                 appendix             1.0
8.0                              0_Classification_Algorithms             1.0
9.0              content/html-css/gitbook/images/favicon.ico             1.0
11.0                              appendix/capstone-workbook             1.0
12.0                             appendix/git/intellij-intro             1.0
13.0          appendix/capstone-workbook/sw-project-planning             1.0
14.0                1-fundamentals/1.1-intro-to-data-science             1.0
15.0                                        appendix/angular             1.0
16.0                              appendix/capstone-workbook             1.0
17.0          appendix/capstone-workbook/sw-project-planning             1.0
18.0                                         1._Fundamentals             1.0
19.0                  1-fundamentals/2.4-more-excel-features             1.0
21.0                1-fundamentals/1.2-data-science-pipeline             1.0
22.0                  1-fundamentals/1-fundamentals-overview             1.0
23.0                  1-fundamentals/1-fundamentals-overview             1.0
24.0                                                    .git             1.0
25.0                                        02_listing_files             1.0
26.0                                      3.0-mysql-overview             1.0
27.0                            1-fundamentals/pipeline-demo             1.0
28.0                                                       '             1.0
29.0                  1-fundamentals/1-fundamentals-overview             1.0
31.0                1-fundamentals/1.1-intro-to-data-science             1.0
32.0                1-fundamentals/1.2-data-science-pipeline             1.0
33.0                             1-fundamentals/3-vocabulary             1.0
34.0       10-anomaly-detection/3-discrete-probabilistic-...             1.0
51.0                      1-fundamentals/2.2-excel-functions             1.0
52.0                              appendix/coding-challenges             1.0
53.0                            appendix/angular/controllers             1.0
55.0                         %20https://github.com/RaulCPena             1.0
56.0                                   appendix/cover-letter             1.0
57.0                                                  alumni             1.0
58.0       appendix/further-reading/css-grid-additional-f...             1.0
59.0                                              .gitignore             1.0
61.0                                             RESTful-api             1.0
62.0                           appendix/angular/dependencies             1.0
132.0                                                      .             1.0
133.0                                             10_Project             1.0
134.0                                appendix/angular/models             1.0
135.0                                                   ajax             1.0
137.0                       advanced-topics/building-a-model             1.0
138.0          appendix/extra-challenges/java-file-io-extras             1.0
139.0                                       appendix/angular             1.0
165.0                       advanced-topics/cross-validation             1.0
166.0                     appendix/coding-challenges/amateur             1.0

**create dataframe with only page count and cohort id**

In [185]:
#creating new df
q2_df= df[['endpoint', 'cohort_id','name', 'program_id']]

In [186]:
#Excluding / symbol (in endpoints)
q2_df= q2_df[q2_df.endpoint != '/'].sort_values(by='cohort_id')

In [187]:
#Looking at question 2 values
q2_df

,endpoint,cohort_id,name,program_id
date,,,,
2021-06-15,html-css/css-i/flexbox/flexbox-fundamentals,1.0,Arches,1.0
2018-08-29,jquery/effects,1.0,Arches,1.0
2018-08-29,jquery,1.0,Arches,1.0
2018-06-21,javascript-i/bom-and-dom/dom,1.0,Arches,1.0
2021-07-01,javascript-i/bom-and-dom,1.0,Arches,1.0
...,...,...,...,...
2021-07-12,javascript-ii/map-filter-reduce,NaN,NaN,0.0
2021-07-12,search/search_index.json,NaN,NaN,0.0
2021-07-12,spring/fundamentals/controllers,NaN,NaN,0.0
2021-07-12,search/search_index.json,NaN,NaN,0.0
2021-07-12,java-i/syntax-types-and-variables,NaN,NaN,0.0

**aggregate page views**

In [197]:
# value counts of endpoint by cohort_id
# c = q2_df.groupby('cohort_id')['endpoint'].value_counts()

# c

In [166]:
# creating dataframe for full stack program
full_stack_df= q2_df[q2_df['program_id']==1]

In [172]:
full_stack_df

,endpoint,cohort_id,name,program_id,pages_viewed_daily
date,,,,,
2021-06-15,html-css/css-i/flexbox/flexbox-fundamentals,1.0,Arches,1.0,3224
2018-08-29,jquery/effects,1.0,Arches,1.0,597
2018-08-29,jquery,1.0,Arches,1.0,597
2018-06-21,javascript-i/bom-and-dom/dom,1.0,Arches,1.0,900
2021-07-01,javascript-i/bom-and-dom,1.0,Arches,1.0,2161
...,...,...,...,...,...
2021-06-08,content/php_i/types-and-variables-i/intergers-...,19.0,Quincy,1.0,1747
2018-06-10,java-ii,19.0,Quincy,1.0,146
2021-06-08,content/html-css/gitbook/images/favicon.ico,19.0,Quincy,1.0,1747
2021-06-08,content/html-css,19.0,Quincy,1.0,1747
2018-06-10,java-ii/inheritance-and-polymorphism,19.0,Quincy,1.0,146

In [200]:
#create list for for loop
fs_list= full_stack_df['cohort_id'].unique().tolist()

In [202]:

full_stack_df.groupby('endpoint')['cohort_id'].value_counts()

endpoint                                  cohort_id
0_Classification_Algorithms               1.0           1
                                          8.0           1
1-fundamentals/1.1-intro-to-data-science  7.0           7
                                          19.0          2
                                          14.0          1
                                                       ..
web-design/ux/layout                      14.0          7
                                          1.0           1
web-design/ux/purpose                     17.0         21
                                          14.0          8
                                          1.0           2
Name: cohort_id, Length: 2726, dtype: int64

In [218]:
#count the number of times they went to that page
for i in fs_list:
    full_stack_df[full_stack_df['cohort_id'] == i]
    fs_new_df=pd.DataFrame(full_stack_df.groupby('endpoint')['cohort_id'].value_counts())

In [220]:
fs_new_df.rename(columns={'cohort_id': 'count'})

                                                    count
endpoint                                 cohort_id
0_Classification_Algorithms              1.0            1
                                         8.0            1
1-fundamentals/1.1-intro-to-data-science 7.0            7
                                         19.0           2
                                         14.0           1
...                                                   ...
web-design/ux/layout                     14.0           7
                                         1.0            1
web-design/ux/purpose                    17.0          21
                                         14.0           8
                                         1.0            2

[2726 rows x 1 columns]

In [204]:
full_stack_df

,endpoint,cohort_id,name,program_id,pages_viewed_daily,count
date,,,,,,
2021-06-15,html-css/css-i/flexbox/flexbox-fundamentals,1.0,Arches,1.0,3224,NaN
2018-08-29,jquery/effects,1.0,Arches,1.0,597,NaN
2018-08-29,jquery,1.0,Arches,1.0,597,NaN
2018-06-21,javascript-i/bom-and-dom/dom,1.0,Arches,1.0,900,NaN
2021-07-01,javascript-i/bom-and-dom,1.0,Arches,1.0,2161,NaN
...,...,...,...,...,...,...
2021-06-08,content/php_i/types-and-variables-i/intergers-...,19.0,Quincy,1.0,1747,NaN
2018-06-10,java-ii,19.0,Quincy,1.0,146,NaN
2021-06-08,content/html-css/gitbook/images/favicon.ico,19.0,Quincy,1.0,1747,NaN
2021-06-08,content/html-css,19.0,Quincy,1.0,1747,NaN
2018-06-10,java-ii/inheritance-and-polymorphism,19.0,Quincy,1.0,146,NaN

In [169]:
# creating dataframe for java
java_df= q2_df[q2_df['program_id']==2]

In [171]:
java_df

,endpoint,cohort_id,name,program_id,pages_viewed_daily
date,,,,,
2018-06-16,slides/mvc,15.0,Mammoth,2.0,152
2018-06-16,java-iii/user-input,15.0,Mammoth,2.0,152
2018-11-05,content/html-css/gitbook/images/favicon.ico,15.0,Mammoth,2.0,708
2018-06-15,java-ii/object-oriented-programming,15.0,Mammoth,2.0,295
2018-06-15,slides/interfaces_and_abstract_classes,15.0,Mammoth,2.0,295
...,...,...,...,...,...
2021-04-24,javascript-i/introduction/primitive-types,139.0,Oberon,2.0,324
2021-04-29,javascript-i/introduction/operators,139.0,Oberon,2.0,1716
2021-05-04,examples/css/css_selectors.html,139.0,Oberon,2.0,2040
2021-05-04,java-i,139.0,Oberon,2.0,2040
2021-05-04,html-css/css-i/introduction,139.0,Oberon,2.0,2040

In [173]:
# creating dataframe for Data Science
ds_df= q2_df[q2_df['program_id']==3]

In [174]:
ds_df

,endpoint,cohort_id,name,program_id,pages_viewed_daily
date,,,,,
2020-04-21,7-classification/5-evaluation,34.0,Bayes,3.0,1177
2019-12-02,8-clustering/1-overview,34.0,Bayes,3.0,968
2019-12-10,11-nlp/5-explore,34.0,Bayes,3.0,1081
2019-12-10,11-nlp/5-explore,34.0,Bayes,3.0,1081
2019-12-02,8-clustering/Hospital-Distance-Clusters.jpg,34.0,Bayes,3.0,968
...,...,...,...,...,...
2021-03-19,fundamentals/data-science-pipeline,137.0,Florence,3.0,2974
2021-03-19,fundamentals/data-science-pipeline,137.0,Florence,3.0,2974
2021-03-19,fundamentals/data-science-pipeline,137.0,Florence,3.0,2974
2021-03-19,regression/feature-engineering,137.0,Florence,3.0,2974
2021-03-19,fundamentals/pipeline-demo,137.0,Florence,3.0,2974

In [175]:
# creating dataframe for Front end 
fe_df= q2_df[q2_df['program_id']==4]

In [176]:
fe_df

,endpoint,cohort_id,name,program_id,pages_viewed_daily
date,,,,,
2018-03-22,content/html-css/introduction.html,9.0,Apollo,4.0,711
2018-03-22,content/html-css,9.0,Apollo,4.0,711
2018-03-22,content/html-css/gitbook/images/favicon.ico,9.0,Apollo,4.0,711
2018-03-22,content/html-css,9.0,Apollo,4.0,711

In [110]:
# xy= df[df.endpoint != '/'].groupby(['endpoint', 'cohort_id']).count()

In [111]:
# xy[['user_id']].tail(15)

**get standard deviation or range (variance) for page views for each page and each cohort**

# 6. What topics are grads continuing to reference after graduation and into their jobs (for each program)?

# compute features
- compute midband
- compute standard deviation
- compute upper & lower band
- create df with metrics
- compute %b
- add user_id to dataframe

# Plot

# Search for anomalies